### ISSUE TITLE
run script appears, many nans

### ISSUE THREAD

**Issue by Adorablepet** [dapengchen123/crf_affinity#3]
Hello,
        Thank you!!
        Environment: Pytorch 0.4.1 Python3.5 CUDA 8.0 GPU: Taitan xp
        Problem: trainers.py print('gallery scores') print(gallery_scores4) 
        appear: gallery scores
                     tensor([nan,nan,.....nan],
                         ..............................)
       RuntimeError: cudaEventSynchronize in future:: wait: device-side assert triggered， Last program crash
      Please help me, thanks.

**Comment by dapengchen123** [comment]
@Adorablepet Did you use the pytorch 0.4 branch, the master branch is for pytorch 0.3.0?

**Comment by Adorablepet** [comment]
Do you think it is possible to be caused by the framework?I use pytorch0.4.1,I try it again with pytorch0.4.The master has two versions, respectively pytorch 0.4 , pytorch 0.3.Which one should I use?Thank you!!

**Comment by Adorablepet** [comment]
I see. Thank you!! I try it again.

**Comment by Adorablepet** [comment]
@dapengchen123 I think you should update ‘README.md’, not very clear, personal advice.Can you write in detail, thank you！！！

**Comment by Adorablepet** [comment]
@dapengchen123 I have solved this error, thanks.

**Comment by dapengchen123** [comment]
@Adorablepet  I will update the readme file, thanks.

**Comment by Huang-3** [comment]
@Adorablepet I also got the same error, how did you solve the problem?
